version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: careem-falcon-postgres
    environment:
      POSTGRES_USER: usman
      POSTGRES_PASSWORD: usman
      POSTGRES_DB: careemDb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
